In [1]:
import pandas as pd
df = pd.read_csv('source/dataset_60.csv')
df.head()

,Unnamed: 0,class,course,speed,row,column,hour_sin,hour_cos,day_sin,day_cos,month_sin,month_cos,target,next_status_60_column,next_status_60_row
0,0,0.0,0.571429,0.666667,0.936340,0.78750,0.50000,1.000000,0.052528,0.71832,0.071797,0.75,675,129.0,340.0
1,1,0.0,0.571429,0.666667,0.936340,0.78750,0.50000,1.000000,0.052528,0.71832,0.071797,0.75,675,129.0,340.0
2,2,0.0,0.571429,0.666667,0.925729,0.79375,0.50000,1.000000,0.052528,0.71832,0.071797,0.75,675,129.0,340.0
3,3,0.0,0.571429,0.333333,0.907162,0.80000,0.50000,1.000000,0.052528,0.71832,0.071797,0.75,794,128.0,342.0
4,4,0.0,0.000000,0.333333,0.901857,0.80625,0.62941,0.982963,0.052528,0.71832,0.071797,0.75,1110,127.0,348.0

In [2]:
features = ['class', 'course', 'speed', 'row','column','hour_sin','hour_cos','day_sin','day_cos', 'month_sin', 'month_cos']

In [3]:
X = df[features]
X.corr()

,class,course,speed,row,column,hour_sin,hour_cos,day_sin,day_cos,month_sin,month_cos
class,1.000000,0.059108,0.352632,0.088959,-0.029997,-0.075373,0.072706,-0.100806,0.167526,-0.035163,0.173021
course,0.059108,1.000000,0.055520,0.076213,-0.030231,-0.004562,0.006304,-0.037811,0.017572,-0.032579,0.022863
speed,0.352632,0.055520,1.000000,0.242343,-0.157942,-0.033448,0.009551,-0.137627,-0.015598,-0.140067,0.009241
row,0.088959,0.076213,0.242343,1.000000,-0.256813,0.017089,0.006235,-0.386379,0.122780,-0.338992,0.186445
column,-0.029997,-0.030231,-0.157942,-0.256813,1.000000,0.018432,-0.024760,0.130737,-0.009765,0.127152,-0.028259
hour_sin,-0.075373,-0.004562,-0.033448,0.017089,0.018432,1.000000,0.002376,-0.011924,0.012911,-0.008242,0.014245
hour_cos,0.072706,0.006304,0.009551,0.006235,-0.024760,0.002376,1.000000,-0.002921,-0.007400,-0.007006,-0.004413
day_sin,-0.100806,-0.037811,-0.137627,-0.386379,0.130737,-0.011924,-0.002921,1.000000,-0.268266,0.902732,-0.425067
day_cos,0.167526,0.017572,-0.015598,0.122780,-0.009765,0.012911,-0.007400,-0.268266,1.000000,0.107512,0.976339
month_sin,-0.035163,-0.032579,-0.140067,-0.338992,0.127152,-0.008242,-0.007006,0.902732,0.107512,1.000000,-0.058703
month_cos,0.173021,0.022863,0.009241,0.186445,-0.028259,0.014245,-0.004413,-0.425067,0.976339,-0.058703,1.000000